<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>si.sunesis.interoperability.lpc</groupId>
    <artifactId>legacy-protocol-converter</artifactId>
    <version>1.6.1</version>
    <packaging>pom</packaging>
    <modules>
        <module>transformation-framework</module>
    </modules>

    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>

        <lombok.version>1.18.36</lombok.version>

        <kumuluzee.version>4.1.0</kumuluzee.version>
        <kumuluzee-logs.version>1.4.6</kumuluzee-logs.version>
        <kumuluzee-cors.version>2.0.0</kumuluzee-cors.version>
        <kumuluzee-health.version>2.5.0</kumuluzee-health.version>
        <kumuluzee-metrics.version>3.0.0</kumuluzee-metrics.version>
        <kumuluzee-config-mp.version>2.0.0</kumuluzee-config-mp.version>

        <jakarta-xml.bind-api.version>4.0.2</jakarta-xml.bind-api.version>
        <jaxb-impl.version>4.0.5</jaxb-impl.version>

        <jserialcomm.version>2.11.0</jserialcomm.version>

        <interoperability-common.version>1.4.0</interoperability-common.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <version>${lombok.version}</version>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>com.kumuluz.ee.logs</groupId>
            <artifactId>kumuluzee-logs-log4j2</artifactId>
            <version>${kumuluzee-logs.version}</version>
        </dependency>

        <dependency>
            <groupId>si.sunesis.interoperability.common</groupId>
            <artifactId>common</artifactId>
            <version>${interoperability-common.version}</version>
        </dependency>

        <dependency>
            <groupId>si.sunesis.interoperability.common</groupId>
            <artifactId>nats</artifactId>
            <version>${interoperability-common.version}</version>
        </dependency>

        <dependency>
            <groupId>si.sunesis.interoperability.common</groupId>
            <artifactId>mqtt</artifactId>
            <version>${interoperability-common.version}</version>
        </dependency>

        <dependency>
            <groupId>si.sunesis.interoperability.common</groupId>
            <artifactId>modbus</artifactId>
            <version>${interoperability-common.version}</version>
        </dependency>

        <dependency>
            <groupId>si.sunesis.interoperability.common</groupId>
            <artifactId>rabbitmq</artifactId>
            <version>${interoperability-common.version}</version>
        </dependency>

    </dependencies>

    <dependencyManagement>
        <dependencies>
            <!-- KumuluzEE BOM -->
            <dependency>
                <groupId>com.kumuluz.ee</groupId>
                <artifactId>kumuluzee-bom</artifactId>
                <version>${kumuluzee.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.kumuluz.ee.cors</groupId>
                <artifactId>kumuluzee-cors</artifactId>
                <version>${kumuluzee-cors.version}</version>
            </dependency>

            <!-- JAXB -->
            <dependency>
                <groupId>jakarta.xml.bind</groupId>
                <artifactId>jakarta.xml.bind-api</artifactId>
                <version>${jakarta-xml.bind-api.version}</version>
            </dependency>

            <dependency>
                <groupId>com.sun.xml.bind</groupId>
                <artifactId>jaxb-impl</artifactId>
                <version>${jaxb-impl.version}</version>
                <scope>runtime</scope>
            </dependency>

            <!-- Modbus serial communication -->
            <dependency>
                <groupId>com.fazecast</groupId>
                <artifactId>jSerialComm</artifactId>
                <version>${jserialcomm.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

</project>