kumuluzee:
  name: legacy-protocol-converter
  server:
    http:
      port: 9094
  version: 1.6.0
  env:
    name: prod
  cors-filter:
    servlet:
      enabled: true
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, HEAD, OPTIONS, DELETE"
  health:
    servlet:
      mapping: health
      enabled: true
    logs:
      enabled: false
  metrics:
    servlet:
      mapping: /metrics/*
      enabled: true
